server:
  port: 8082
  servlet:
    contextPath: /cyberware
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cyberware?user=root&password=password
    driverClassName: com.mysql.cj.jdbc.Driver